# Generated by Django 5.2 on 2025-04-20 08:53

import django.core.validators
import django.utils.timezone
import indexer_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, help_text='Unique title for the document', max_length=255, unique=True)),
                ('content', models.TextField(help_text='Original document content')),
                ('processed_content', models.TextField(blank=True, help_text='Preprocessed content for TF-IDF calculation')),
                ('uploaded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp of document upload')),
                ('tfidf_vector', models.JSONField(blank=True, help_text='TF-IDF vector data stored as JSON', null=True)),
                ('file_type', models.CharField(choices=[('txt', 'Text File'), ('pdf', 'PDF Document'), ('doc', 'Word Document'), ('docx', 'Word Document (DOCX)')], default='txt', help_text='Type of the document file', max_length=10)),
                ('file_size', models.IntegerField(help_text='Size of the document in bytes', validators=[django.core.validators.MinValueValidator(1), indexer_app.models.validate_file_size])),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['title'], name='indexer_app_title_4f5685_idx'), models.Index(fields=['uploaded_at'], name='indexer_app_uploade_d43828_idx'), models.Index(fields=['file_type'], name='indexer_app_file_ty_18da8d_idx')],
            },
        ),
    ]
