# Generated by Django 5.2 on 2025-04-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content_vocabulary',
            field=models.JSONField(blank=True, default=list, help_text='Processed words from the content', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='title_vocabulary',
            field=models.JSONField(blank=True, default=list, help_text='Processed words from the title', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='word_frequencies',
            field=models.JSONField(default=dict, help_text='Word frequencies in the document'),
        ),
    ]
